services:
  mysql:
    image: mysql:8.4
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ccd_cafe
      MYSQL_USER: ccd_user
      MYSQL_PASSWORD: ccd_password
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/sql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    container_name: api
    build: ./backend
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      PORT: 4000
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: ccd_user
      DB_PASSWORD: ccd_password
      DB_NAME: ccd_cafe
      JWT_SECRET: supersecretjwtkey
    ports:
      - '4000:4000'
    restart: unless-stopped
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - api
    environment:
      # Will use env var if set, otherwise fall back to localhost:4000
      VITE_API_BASE_URL: ${VITE_API_BASE_URL:-http://localhost:4000}
      # VITE_API_BASE_URL: http://api:4000 # locally within docker-compose network
      # VITE_API_BASE_URL: http://51.20.119.78:4000
      # or better, use the DNS:
      # VITE_API_BASE_URL: http://ec2-51-20-119-78.eu-north-1.compute.amazonaws.com:4000
      # VITE_API_BASE_URL: http://localhost:4000 # Use this line for local development To avoid breaking this every time the IP changes:
    ports:
      - '5173:5173'
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev -- --host 0.0.0.0

volumes:
  mysql_data:
